name: nanopc-t4
version: 16-0.1
summary: NanoPC T-4 boot support
description: |
 Support files for booting a NanoPC T-4 Rockchip 3399 board.
type: gadget
architectures:
  - build-on: amd64
    run-on: arm64

confinement: strict
grade: stable

parts:
  uboot-nanopc:
    plugin: nil
    source: git://git.denx.de/u-boot.git
    source-branch: v2018.11
    override-build: |
      git apply ../../../nanopc-t4.patch
      TCHAINVER="$(wget -q -O - \
                 https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/| \
                 html2text -width 200|grep 'x86_64_aarch64-linux-gnu.tar.xz '|cut -d' ' -f2)"
      wget https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/$TCHAINVER
      tar xf $TCHAINVER
      mv $(echo $TCHAINVER|sed 's/.tar.xz$//') toolchain
      CROSS_COMPILE=$(pwd)/toolchain/bin/aarch64-linux-gnu- make nanopi4_defconfig
      CROSS_COMPILE=$(pwd)/toolchain/bin/aarch64-linux-gnu- make

      mkdir -p $SNAPCRAFT_PART_INSTALL/boot-assets
      cp u-boot.img $SNAPCRAFT_PART_INSTALL/boot-assets/

      #tools/mkimage -n rk3288 -T rksd -d spl/u-boot-spl-dtb.bin $SNAPCRAFT_PART_INSTALL/boot-assets/u-boot.img
      #cat u-boot-dtb.bin >> $SNAPCRAFT_PART_INSTALL/boot-assets/u-boot.img

      tools/mkenvimage -r -s 131072 -o $SNAPCRAFT_PART_INSTALL/uboot.env ../../../uboot.env.in
      ln -s uboot.env $SNAPCRAFT_PART_INSTALL/uboot.conf
    build-packages:
      - bc
      - bison
      - build-essential
      - device-tree-compiler
      - flex
      - libpython2.7-dev
      - python-minimal
      - gcc-aarch64-linux-gnu
